services:
  db:
    image: postgres:18
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - ${EXPRESS_PORT}:3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  db-data:
