services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB} -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_client:
    image: dpage/pgadmin4
    container_name: db_client
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - ${EXPRESS_PORT}:3000
    depends_on:
      db:
       condition: service_healthy
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  db-data:
