--
-- PostgreSQL database dump
--

\restrict QwcBeQgOnXhI3NSgkul7cOxi1a5pUmPkLWpkY4gIbQeSsyfEKwhiCDNjvTqqItH

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: products; Type: TABLE; Schema: public; Owner: innowitzkie
--

CREATE TABLE public.products (
    product_id integer NOT NULL,
    product_name character varying(255) NOT NULL,
    product_unit_price integer NOT NULL,
    product_quantity integer NOT NULL,
    is_still_offered boolean NOT NULL
);


ALTER TABLE public.products OWNER TO innowitzkie;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: innowitzkie
--

ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_items; Type: TABLE; Schema: public; Owner: innowitzkie
--

CREATE TABLE public.transaction_items (
    item_id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    product_id integer NOT NULL,
    product_name character varying(255) NOT NULL,
    product_unit_price integer NOT NULL,
    quantity_bought integer NOT NULL
);


ALTER TABLE public.transaction_items OWNER TO innowitzkie;

--
-- Name: transaction_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: innowitzkie
--

ALTER TABLE public.transaction_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: innowitzkie
--

CREATE TABLE public.transactions (
    transaction_id bigint NOT NULL,
    prev_txn_id bigint,
    transaction_timestamp timestamp with time zone NOT NULL,
    payment_type character varying(255) NOT NULL,
    payment_refstr character varying(255),
    created_by integer NOT NULL,
    voided_at timestamp with time zone,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public.transactions OWNER TO innowitzkie;

--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: innowitzkie
--

ALTER TABLE public.transactions ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: innowitzkie
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    is_admin boolean NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.users OWNER TO innowitzkie;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: innowitzkie
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: innowitzkie
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- Name: products products_product_name_key; Type: CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_product_name_key UNIQUE (product_name);


--
-- Name: transaction_items transaction_items_pkey; Type: CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_pkey PRIMARY KEY (item_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: pk_item_id; Type: INDEX; Schema: public; Owner: eggrolls
--

CREATE UNIQUE INDEX pk_item_id ON public.transaction_items USING btree (item_id);


--
-- Name: pk_product_id; Type: INDEX; Schema: public; Owner: eggrolls
--

CREATE UNIQUE INDEX pk_product_id ON public.products USING btree (product_id);


--
-- Name: pk_transaction_id; Type: INDEX; Schema: public; Owner: eggrolls
--

CREATE UNIQUE INDEX pk_transaction_id ON public.transactions USING btree (transaction_id);


--
-- Name: pk_user_id; Type: INDEX; Schema: public; Owner: eggrolls
--

CREATE UNIQUE INDEX pk_user_id ON public.users USING btree (user_id);


--
-- Name: uq_product_name; Type: INDEX; Schema: public; Owner: eggrolls
--

CREATE UNIQUE INDEX uq_product_name ON public.products USING btree (product_name);


--
-- Name: uq_username; Type: INDEX; Schema: public; Owner: eggrolls
--

CREATE UNIQUE INDEX uq_username ON public.users USING btree (username);


--
-- Name: transaction_items transaction_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON UPDATE CASCADE;


--
-- Name: transaction_items transaction_items_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id) ON UPDATE CASCADE;


--
-- Name: transactions transactions_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: eggrolls
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id) ON UPDATE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict QwcBeQgOnXhI3NSgkul7cOxi1a5pUmPkLWpkY4gIbQeSsyfEKwhiCDNjvTqqItH

